// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hnr.sql

package queries

import (
	"context"
)

const accumulateUserTorrentBytes = `-- name: AccumulateUserTorrentBytes :exec
INSERT INTO hnr_tracking (
    id, user_id, torrent_id, downloaded_at,
    seed_time, required_seed_time,
    is_hnr, is_exempt,
    uploaded, downloaded
)
VALUES ($1, $2, $3, NOW(), 0, $4, false, false, $5, $6)
ON CONFLICT (user_id, torrent_id) DO UPDATE
   SET uploaded   = hnr_tracking.uploaded   + EXCLUDED.uploaded,
       downloaded = hnr_tracking.downloaded + EXCLUDED.downloaded
`

type AccumulateUserTorrentBytesParams struct {
	ID               string
	UserID           string
	TorrentID        string
	RequiredSeedTime int32
	Uploaded         int64
	Downloaded       int64
}

// Incrementally records per-(user, torrent) byte totals on every
// announce. Creates the tracking row on the first non-zero delta so
// the Downloads page in the web UI surfaces the entry as soon as the
// user starts leeching, well before completion. The composite UNIQUE
// on (user_id, torrent_id) makes the upsert race-free.
func (q *Queries) AccumulateUserTorrentBytes(ctx context.Context, arg AccumulateUserTorrentBytesParams) error {
	_, err := q.db.Exec(ctx, accumulateUserTorrentBytes,
		arg.ID,
		arg.UserID,
		arg.TorrentID,
		arg.RequiredSeedTime,
		arg.Uploaded,
		arg.Downloaded,
	)
	return err
}

const addSeedTime = `-- name: AddSeedTime :exec
UPDATE hnr_tracking
   SET seed_time    = seed_time + $1,
       completed_at = CASE
         WHEN completed_at IS NULL
          AND seed_time + $1 >= required_seed_time
         THEN NOW()
         ELSE completed_at
       END,
       is_hnr       = CASE
         WHEN completed_at IS NULL
          AND seed_time + $1 >= required_seed_time
         THEN false
         ELSE is_hnr
       END
 WHERE user_id = $2
   AND torrent_id = $3
   AND is_exempt = false
   AND completed_at IS NULL
`

type AddSeedTimeParams struct {
	SeedTime  int32
	UserID    string
	TorrentID string
}

// Adds `additional` seconds to a peer's seed time. If the cumulative total
// crosses required_seed_time the row is also stamped completed_at = NOW()
// and is_hnr cleared, all in one atomic UPDATE.
func (q *Queries) AddSeedTime(ctx context.Context, arg AddSeedTimeParams) error {
	_, err := q.db.Exec(ctx, addSeedTime, arg.SeedTime, arg.UserID, arg.TorrentID)
	return err
}

const createHnrEntry = `-- name: CreateHnrEntry :exec
INSERT INTO hnr_tracking (
    id, user_id, torrent_id,
    downloaded_at, seed_time, required_seed_time,
    is_hnr, is_exempt
)
VALUES ($1, $2, $3, NOW(), 0, $4, false, false)
ON CONFLICT (user_id, torrent_id) DO NOTHING
`

type CreateHnrEntryParams struct {
	ID               string
	UserID           string
	TorrentID        string
	RequiredSeedTime int32
}

// Inserts a new hit-and-run row when a user completes a torrent for the
// first time. Idempotent thanks to the (user_id, torrent_id) UNIQUE.
func (q *Queries) CreateHnrEntry(ctx context.Context, arg CreateHnrEntryParams) error {
	_, err := q.db.Exec(ctx, createHnrEntry,
		arg.ID,
		arg.UserID,
		arg.TorrentID,
		arg.RequiredSeedTime,
	)
	return err
}

const findUserAndTorrentByPasskeyAndHash = `-- name: FindUserAndTorrentByPasskeyAndHash :one
SELECT u.id AS user_id, t.id AS torrent_id
  FROM users u, torrents t
 WHERE u.passkey = $1
   AND t.info_hash = $2
   AND t.is_active = true
 LIMIT 1
`

type FindUserAndTorrentByPasskeyAndHashParams struct {
	Passkey  string
	InfoHash string
}

type FindUserAndTorrentByPasskeyAndHashRow struct {
	UserID    string
	TorrentID string
}

// Resolves (passkey, info_hash) to (user_id, torrent_id). Used right
// before HnR writes so we don't have to round-trip twice.
func (q *Queries) FindUserAndTorrentByPasskeyAndHash(ctx context.Context, arg FindUserAndTorrentByPasskeyAndHashParams) (FindUserAndTorrentByPasskeyAndHashRow, error) {
	row := q.db.QueryRow(ctx, findUserAndTorrentByPasskeyAndHash, arg.Passkey, arg.InfoHash)
	var i FindUserAndTorrentByPasskeyAndHashRow
	err := row.Scan(&i.UserID, &i.TorrentID)
	return i, err
}
