// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hnr.sql

package queries

import (
	"context"
)

const addSeedTime = `-- name: AddSeedTime :exec
UPDATE hnr_tracking
   SET seed_time    = seed_time + $1,
       completed_at = CASE
         WHEN completed_at IS NULL
          AND seed_time + $1 >= required_seed_time
         THEN NOW()
         ELSE completed_at
       END,
       is_hnr       = CASE
         WHEN completed_at IS NULL
          AND seed_time + $1 >= required_seed_time
         THEN false
         ELSE is_hnr
       END
 WHERE user_id = $2
   AND torrent_id = $3
   AND is_exempt = false
   AND completed_at IS NULL
`

type AddSeedTimeParams struct {
	SeedTime  int32
	UserID    string
	TorrentID string
}

// Adds `additional` seconds to a peer's seed time. If the cumulative total
// crosses required_seed_time the row is also stamped completed_at = NOW()
// and is_hnr cleared, all in one atomic UPDATE.
func (q *Queries) AddSeedTime(ctx context.Context, arg AddSeedTimeParams) error {
	_, err := q.db.Exec(ctx, addSeedTime, arg.SeedTime, arg.UserID, arg.TorrentID)
	return err
}

const bumpUserTorrentBytes = `-- name: BumpUserTorrentBytes :execrows
UPDATE hnr_tracking
   SET uploaded   = uploaded   + $1,
       downloaded = downloaded + $2
 WHERE user_id    = $3
   AND torrent_id = $4
`

type BumpUserTorrentBytesParams struct {
	Uploaded   int64
	Downloaded int64
	UserID     string
	TorrentID  string
}

// Fast path on every announce: increment the byte totals for an
// existing (user, torrent) pair. Returns the row count so the caller
// can fall through to InsertUserTorrentBytes when the row hasn't been
// created yet (rare — the API stamps a row on the first .torrent
// download, and the tracker's own HnR completion path also creates
// one). Plain UPDATE costs no crypto-rand, no constraint check, no
// dead-tuple churn — the previous INSERT … ON CONFLICT path paid all
// of those on every single announce.
func (q *Queries) BumpUserTorrentBytes(ctx context.Context, arg BumpUserTorrentBytesParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpUserTorrentBytes,
		arg.Uploaded,
		arg.Downloaded,
		arg.UserID,
		arg.TorrentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createHnrEntry = `-- name: CreateHnrEntry :exec
INSERT INTO hnr_tracking (
    id, user_id, torrent_id,
    downloaded_at, seed_time, required_seed_time,
    is_hnr, is_exempt
)
VALUES ($1, $2, $3, NOW(), 0, $4, false, false)
ON CONFLICT (user_id, torrent_id) DO NOTHING
`

type CreateHnrEntryParams struct {
	ID               string
	UserID           string
	TorrentID        string
	RequiredSeedTime int32
}

// Inserts a new hit-and-run row when a user completes a torrent for the
// first time. Idempotent thanks to the (user_id, torrent_id) UNIQUE.
func (q *Queries) CreateHnrEntry(ctx context.Context, arg CreateHnrEntryParams) error {
	_, err := q.db.Exec(ctx, createHnrEntry,
		arg.ID,
		arg.UserID,
		arg.TorrentID,
		arg.RequiredSeedTime,
	)
	return err
}

const findUserAndTorrentByPasskeyAndHash = `-- name: FindUserAndTorrentByPasskeyAndHash :one
SELECT u.id AS user_id, t.id AS torrent_id
  FROM users u, torrents t
 WHERE u.passkey = $1
   AND t.info_hash = $2
   AND t.is_active = true
 LIMIT 1
`

type FindUserAndTorrentByPasskeyAndHashParams struct {
	Passkey  string
	InfoHash string
}

type FindUserAndTorrentByPasskeyAndHashRow struct {
	UserID    string
	TorrentID string
}

// Resolves (passkey, info_hash) to (user_id, torrent_id). Used right
// before HnR writes so we don't have to round-trip twice.
func (q *Queries) FindUserAndTorrentByPasskeyAndHash(ctx context.Context, arg FindUserAndTorrentByPasskeyAndHashParams) (FindUserAndTorrentByPasskeyAndHashRow, error) {
	row := q.db.QueryRow(ctx, findUserAndTorrentByPasskeyAndHash, arg.Passkey, arg.InfoHash)
	var i FindUserAndTorrentByPasskeyAndHashRow
	err := row.Scan(&i.UserID, &i.TorrentID)
	return i, err
}

const insertUserTorrentBytes = `-- name: InsertUserTorrentBytes :exec
INSERT INTO hnr_tracking (
    id, user_id, torrent_id, downloaded_at,
    seed_time, required_seed_time,
    is_hnr, is_exempt,
    uploaded, downloaded
)
VALUES ($1, $2, $3, NOW(), 0, $4, false, false, $5, $6)
ON CONFLICT (user_id, torrent_id) DO NOTHING
`

type InsertUserTorrentBytesParams struct {
	ID               string
	UserID           string
	TorrentID        string
	RequiredSeedTime int32
	Uploaded         int64
	Downloaded       int64
}

// Cold path used only when BumpUserTorrentBytes touched zero rows —
// typically the very first delta we receive for a user×torrent pair
// when there's no .torrent-click stamp yet. ON CONFLICT DO NOTHING
// keeps the call race-safe against a concurrent first-announce.
func (q *Queries) InsertUserTorrentBytes(ctx context.Context, arg InsertUserTorrentBytesParams) error {
	_, err := q.db.Exec(ctx, insertUserTorrentBytes,
		arg.ID,
		arg.UserID,
		arg.TorrentID,
		arg.RequiredSeedTime,
		arg.Uploaded,
		arg.Downloaded,
	)
	return err
}
