// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	// Incrementally records per-(user, torrent) byte totals on every
	// announce. Creates the tracking row on the first non-zero delta so
	// the Downloads page in the web UI surfaces the entry as soon as the
	// user starts leeching, well before completion. The composite UNIQUE
	// on (user_id, torrent_id) makes the upsert race-free.
	AccumulateUserTorrentBytes(ctx context.Context, arg AccumulateUserTorrentBytesParams) error
	// Adds `additional` seconds to a peer's seed time. If the cumulative total
	// crosses required_seed_time the row is also stamped completed_at = NOW()
	// and is_hnr cleared, all in one atomic UPDATE.
	AddSeedTime(ctx context.Context, arg AddSeedTimeParams) error
	// Inserts a new hit-and-run row when a user completes a torrent for the
	// first time. Idempotent thanks to the (user_id, torrent_id) UNIQUE.
	CreateHnrEntry(ctx context.Context, arg CreateHnrEntryParams) error
	// Returns the active torrent matching the given hex info_hash, or no rows
	// if either it doesn't exist or it's been deactivated.
	FindActiveTorrentByInfoHash(ctx context.Context, infoHash string) (string, error)
	// Resolves (passkey, info_hash) to (user_id, torrent_id). Used right
	// before HnR writes so we don't have to round-trip twice.
	FindUserAndTorrentByPasskeyAndHash(ctx context.Context, arg FindUserAndTorrentByPasskeyAndHashParams) (FindUserAndTorrentByPasskeyAndHashRow, error)
	// Returns the columns the tracker needs to validate a passkey on every announce.
	FindUserByPasskey(ctx context.Context, passkey string) (FindUserByPasskeyRow, error)
	// Returns the raw string value for a settings key, or no rows if unset.
	// The tracker layers a TTL cache on top of this — see internal/db/cache.go.
	GetSetting(ctx context.Context, key string) (string, error)
	// Adds upload/download deltas to the user identified by passkey.
	IncrementUserStats(ctx context.Context, arg IncrementUserStatsParams) error
}

var _ Querier = (*Queries)(nil)
