// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package queries

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value
  FROM settings
 WHERE key = $1
 LIMIT 1
`

// Returns the raw string value for a settings key, or no rows if unset.
// The tracker layers a TTL cache on top of this — see internal/db/cache.go.
func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
