// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrents.sql

package queries

import (
	"context"
)

const findActiveTorrentByInfoHash = `-- name: FindActiveTorrentByInfoHash :one
SELECT id
  FROM torrents
 WHERE info_hash = $1
   AND is_active = true
 LIMIT 1
`

// Returns the active torrent matching the given hex info_hash, or no rows
// if either it doesn't exist or it's been deactivated.
func (q *Queries) FindActiveTorrentByInfoHash(ctx context.Context, infoHash string) (string, error) {
	row := q.db.QueryRow(ctx, findActiveTorrentByInfoHash, infoHash)
	var id string
	err := row.Scan(&id)
	return id, err
}
