// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrents.sql

package queries

import (
	"context"
)

const findActiveTorrentByInfoHash = `-- name: FindActiveTorrentByInfoHash :one
SELECT id
  FROM torrents
 WHERE info_hash = $1
   AND is_active = true
 LIMIT 1
`

// Returns the active torrent matching the given hex info_hash, or no rows
// if either it doesn't exist or it's been deactivated.
func (q *Queries) FindActiveTorrentByInfoHash(ctx context.Context, infoHash string) (string, error) {
	row := q.db.QueryRow(ctx, findActiveTorrentByInfoHash, infoHash)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findActiveTorrentByInfoHashV2Short = `-- name: FindActiveTorrentByInfoHashV2Short :one
SELECT id, info_hash
  FROM torrents
 WHERE left(info_hash_v2, 40) = $1::text
   AND is_active = true
 LIMIT 1
`

type FindActiveTorrentByInfoHashV2ShortRow struct {
	ID       string
	InfoHash string
}

// The BEP 52 second swarm.
//
// A v2 or hybrid torrent has two infohashes and a client that supports v2
// announces the SHA-256 one — truncated to 20 bytes, because the tracker
// protocol has no room for 32. That truncation is the first 40 hex characters
// of `info_hash_v2`, which is what this matches.
//
// Returns the canonical `info_hash` alongside the id, and the caller switches
// to it as the swarm key. That is what merges the two halves of a hybrid
// torrent's swarm instead of leaving v1-only and v2-capable peers unable to
// see each other.
//
// Served by `torrents_info_hash_v2_short_idx`, a partial expression index — so
// this costs an index lookup, not a scan, and only v2 rows are in it.
//
// The parameter is cast: `info_hash_v2` is nullable, so sqlc infers a nullable
// argument from a bare comparison and generates `*string` for a value the
// caller always has. The cast is on the parameter, not on the column, so the
// expression index still serves the predicate.
func (q *Queries) FindActiveTorrentByInfoHashV2Short(ctx context.Context, announcedHash string) (FindActiveTorrentByInfoHashV2ShortRow, error) {
	row := q.db.QueryRow(ctx, findActiveTorrentByInfoHashV2Short, announcedHash)
	var i FindActiveTorrentByInfoHashV2ShortRow
	err := row.Scan(&i.ID, &i.InfoHash)
	return i, err
}
