// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"
)

const findUserByPasskey = `-- name: FindUserByPasskey :one
SELECT id, is_banned, uploaded, downloaded
  FROM users
 WHERE passkey = $1
 LIMIT 1
`

type FindUserByPasskeyRow struct {
	ID         string
	IsBanned   bool
	Uploaded   int64
	Downloaded int64
}

// Returns the columns the tracker needs to validate a passkey on every announce.
func (q *Queries) FindUserByPasskey(ctx context.Context, passkey string) (FindUserByPasskeyRow, error) {
	row := q.db.QueryRow(ctx, findUserByPasskey, passkey)
	var i FindUserByPasskeyRow
	err := row.Scan(
		&i.ID,
		&i.IsBanned,
		&i.Uploaded,
		&i.Downloaded,
	)
	return i, err
}

const incrementUserStats = `-- name: IncrementUserStats :exec
UPDATE users
   SET uploaded   = uploaded   + $1,
       downloaded = downloaded + $2
 WHERE passkey = $3
`

type IncrementUserStatsParams struct {
	Uploaded   int64
	Downloaded int64
	Passkey    string
}

// Adds upload/download deltas to the user identified by passkey.
func (q *Queries) IncrementUserStats(ctx context.Context, arg IncrementUserStatsParams) error {
	_, err := q.db.Exec(ctx, incrementUserStats, arg.Uploaded, arg.Downloaded, arg.Passkey)
	return err
}
