-- Generated by drizzle-kit against a snapshot pulled from the migrated
-- schema, so this is the exact diff between what the chain built and what
-- schema.ts declares. It is large for one reason: nobody had run generate
-- since 0006, and push — which had been standing in for it — does not create
-- indexes at all.
--
-- The part that matters operationally: 9 indexes schema.ts declares had never
-- reached a database built by push. Among them the full-text indexes on
-- torrents and tags, and torrents_grouped_idx / torrents_ungrouped_idx, which
-- the grouped catalogue listing rides. Those queries have been sequential
-- scans in production.
--
-- Most of the rest is drizzle renaming and re-forming indexes and keys to its
-- own canonical shape, because the hand-written migrations let Postgres name
-- them. Two changes in there are real, not cosmetic:
--   * torrents_name_trgm_idx moves from gist to gin, which is what schema.ts
--     has declared all along.
--   * users.auth_salt / auth_verifier become NOT NULL. 0008_zke_auth added
--     them nullable and left the NOT NULL step commented out; schema.ts has
--     required them since. Existing rows must have both set, which the one
--     production account does.
--
-- Made idempotent to match the rest of the chain: a database joining partway
-- has to tolerate re-running what it already holds.

ALTER TABLE "roles" DROP CONSTRAINT IF EXISTS "roles_name_key";
--> statement-breakpoint
ALTER TABLE "forum_topics" DROP CONSTRAINT IF EXISTS "forum_topics_author_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "forum_posts" DROP CONSTRAINT IF EXISTS "forum_posts_author_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "torrent_comments" DROP CONSTRAINT IF EXISTS "torrent_comments_author_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "anticheat_flags" DROP CONSTRAINT IF EXISTS "anticheat_flags_user_id_fkey";
--> statement-breakpoint
ALTER TABLE "anticheat_flags" DROP CONSTRAINT IF EXISTS "anticheat_flags_torrent_id_fkey";
--> statement-breakpoint
ALTER TABLE "anticheat_flags" DROP CONSTRAINT IF EXISTS "anticheat_flags_reviewed_by_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_requests" DROP CONSTRAINT IF EXISTS "upload_requests_requester_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_requests" DROP CONSTRAINT IF EXISTS "upload_requests_category_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_requests" DROP CONSTRAINT IF EXISTS "upload_requests_filled_by_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_requests" DROP CONSTRAINT IF EXISTS "upload_requests_filled_torrent_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_request_fill_attempts" DROP CONSTRAINT IF EXISTS "upload_request_fill_attempts_request_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_request_fill_attempts" DROP CONSTRAINT IF EXISTS "upload_request_fill_attempts_user_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_request_fill_attempts" DROP CONSTRAINT IF EXISTS "upload_request_fill_attempts_torrent_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_request_comments" DROP CONSTRAINT IF EXISTS "upload_request_comments_request_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_request_comments" DROP CONSTRAINT IF EXISTS "upload_request_comments_author_id_fkey";
--> statement-breakpoint
ALTER TABLE "upload_request_comments" DROP CONSTRAINT IF EXISTS "upload_request_comments_deleted_by_id_fkey";
--> statement-breakpoint
ALTER TABLE "freeleech_pool_cycles" DROP CONSTRAINT IF EXISTS "freeleech_pool_cycles_triggered_event_id_fkey";
--> statement-breakpoint
ALTER TABLE "freeleech_pool_cycles" DROP CONSTRAINT IF EXISTS "freeleech_pool_cycles_paused_event_created_by_id_fkey";
--> statement-breakpoint
ALTER TABLE "freeleech_pool_cycles" DROP CONSTRAINT IF EXISTS "freeleech_pool_cycles_waiting_on_event_id_fkey";
--> statement-breakpoint
ALTER TABLE "freeleech_pool_contributions" DROP CONSTRAINT IF EXISTS "freeleech_pool_contributions_cycle_id_fkey";
--> statement-breakpoint
ALTER TABLE "freeleech_pool_contributions" DROP CONSTRAINT IF EXISTS "freeleech_pool_contributions_user_id_fkey";
--> statement-breakpoint
ALTER TABLE "categories" DROP CONSTRAINT IF EXISTS "categories_parent_id_fk";
--> statement-breakpoint
ALTER TABLE "torrent_favorites" DROP CONSTRAINT IF EXISTS "torrent_favorites_user_id_fkey";
--> statement-breakpoint
ALTER TABLE "torrent_favorites" DROP CONSTRAINT IF EXISTS "torrent_favorites_torrent_id_fkey";
--> statement-breakpoint
ALTER TABLE "user_follows" DROP CONSTRAINT IF EXISTS "user_follows_follower_id_fkey";
--> statement-breakpoint
ALTER TABLE "user_follows" DROP CONSTRAINT IF EXISTS "user_follows_following_id_fkey";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrent_tags_torrent_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_record_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "categories_parent_name_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "users_banned_until_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "announce_log_created_at_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "announce_log_info_hash_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "invitations_code_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "invitations_created_by_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrent_tags_tag_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_age_tiers_enabled_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_age_tiers_threshold_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_rules_kind_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_seed_count_tiers_enabled_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_seed_count_tiers_threshold_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_events_enabled_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_events_window_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_grants_first_seeder_unique_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_grants_source_user_torrent_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "bonus_grants_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "federated_follows_target_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "federated_follows_unique";
--> statement-breakpoint
DROP INDEX IF EXISTS "federation_peers_instance_id_unique";
--> statement-breakpoint
DROP INDEX IF EXISTS "federation_peers_status_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "federated_identities_unique";
--> statement-breakpoint
DROP INDEX IF EXISTS "notifications_user_created_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "notifications_user_unread_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "recovery_codes_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_content_sig_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_igdb_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_imdb_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_info_hash_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_name_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_openlibrary_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_peer_remote_unique";
--> statement-breakpoint
DROP INDEX IF EXISTS "remote_torrents_tmdb_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "shop_items_enabled_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "shop_purchases_item_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "shop_purchases_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrent_mod_messages_author_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrent_mod_messages_torrent_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "trusted_devices_expires_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "trusted_devices_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "user_notification_channels_user_type_unique";
--> statement-breakpoint
DROP INDEX IF EXISTS "user_notification_routing_pk";
--> statement-breakpoint
DROP INDEX IF EXISTS "user_notification_routing_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "webauthn_credentials_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "anticheat_flags_kind_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "anticheat_flags_no_leecher_open_unique";
--> statement-breakpoint
DROP INDEX IF EXISTS "anticheat_flags_unreviewed_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "anticheat_flags_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "upload_requests_filled_at_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "upload_requests_requester_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "upload_requests_status_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "upload_request_fill_attempts_active_unique";
--> statement-breakpoint
DROP INDEX IF EXISTS "upload_request_fill_attempts_request_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "upload_request_comments_request_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "freeleech_pool_config_singleton";
--> statement-breakpoint
DROP INDEX IF EXISTS "freeleech_pool_windows_kind_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "freeleech_pool_windows_oneoff_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "freeleech_pool_cycles_open_unique";
--> statement-breakpoint
DROP INDEX IF EXISTS "freeleech_pool_cycles_status_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "freeleech_pool_contributions_cycle_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "freeleech_pool_contributions_cycle_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "federation_catalog_removals_cursor_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "categories_parent_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "hnr_status_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "hnr_torrent_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "hnr_user_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "hnr_user_torrent_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "reports_reporter_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "reports_status_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "reports_target_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "site_stats_created_at_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrents_category_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrents_igdb_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrents_info_hash_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrents_name_trgm_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrents_openlibrary_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrents_updated_at_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrents_uploader_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "users_passkey_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "torrent_favorites_user_created_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "user_follows_following_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "user_roles_role_idx";
--> statement-breakpoint
ALTER TABLE "torrent_favorites" DROP CONSTRAINT IF EXISTS "torrent_favorites_pkey";
--> statement-breakpoint
ALTER TABLE "user_follows" DROP CONSTRAINT IF EXISTS "user_follows_pkey";
--> statement-breakpoint
ALTER TABLE "forum_topics" ALTER COLUMN "author_id" DROP NOT NULL;
--> statement-breakpoint
ALTER TABLE "forum_posts" ALTER COLUMN "author_id" DROP NOT NULL;
--> statement-breakpoint
ALTER TABLE "torrent_comments" ALTER COLUMN "author_id" DROP NOT NULL;
--> statement-breakpoint
ALTER TABLE "federation_config" ALTER COLUMN "default_scopes" SET DEFAULT '{"catalog":false,"social":false,"accounts":false,"swarm":false}'::jsonb;
--> statement-breakpoint
ALTER TABLE "federation_peers" ALTER COLUMN "shares_with_them" SET DEFAULT '{"catalog":false,"social":false,"accounts":false,"swarm":false}'::jsonb;
--> statement-breakpoint
ALTER TABLE "federation_peers" ALTER COLUMN "accepts_from_them" SET DEFAULT '{"catalog":false,"social":false,"accounts":false,"swarm":false}'::jsonb;
--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "auth_salt" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "auth_verifier" SET NOT NULL;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conrelid = 'public.torrent_tags'::regclass AND contype = 'p') THEN
    ALTER TABLE "torrent_tags" ADD CONSTRAINT "torrent_tags_torrent_id_tag_id_pk" PRIMARY KEY("torrent_id","tag_id");
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conrelid = 'public.torrent_favorites'::regclass AND contype = 'p') THEN
    ALTER TABLE "torrent_favorites" ADD CONSTRAINT "torrent_favorites_user_id_torrent_id_pk" PRIMARY KEY("user_id","torrent_id");
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conrelid = 'public.user_follows'::regclass AND contype = 'p') THEN
    ALTER TABLE "user_follows" ADD CONSTRAINT "user_follows_follower_id_following_id_pk" PRIMARY KEY("follower_id","following_id");
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'forum_topics_author_id_users_id_fk' AND conrelid = 'public.forum_topics'::regclass) THEN
    ALTER TABLE "forum_topics" ADD CONSTRAINT "forum_topics_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'forum_posts_author_id_users_id_fk' AND conrelid = 'public.forum_posts'::regclass) THEN
    ALTER TABLE "forum_posts" ADD CONSTRAINT "forum_posts_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'torrent_comments_author_id_users_id_fk' AND conrelid = 'public.torrent_comments'::regclass) THEN
    ALTER TABLE "torrent_comments" ADD CONSTRAINT "torrent_comments_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'anticheat_flags_user_id_users_id_fk' AND conrelid = 'public.anticheat_flags'::regclass) THEN
    ALTER TABLE "anticheat_flags" ADD CONSTRAINT "anticheat_flags_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'anticheat_flags_torrent_id_torrents_id_fk' AND conrelid = 'public.anticheat_flags'::regclass) THEN
    ALTER TABLE "anticheat_flags" ADD CONSTRAINT "anticheat_flags_torrent_id_torrents_id_fk" FOREIGN KEY ("torrent_id") REFERENCES "public"."torrents"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'anticheat_flags_reviewed_by_id_users_id_fk' AND conrelid = 'public.anticheat_flags'::regclass) THEN
    ALTER TABLE "anticheat_flags" ADD CONSTRAINT "anticheat_flags_reviewed_by_id_users_id_fk" FOREIGN KEY ("reviewed_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_requests_requester_id_users_id_fk' AND conrelid = 'public.upload_requests'::regclass) THEN
    ALTER TABLE "upload_requests" ADD CONSTRAINT "upload_requests_requester_id_users_id_fk" FOREIGN KEY ("requester_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_requests_category_id_categories_id_fk' AND conrelid = 'public.upload_requests'::regclass) THEN
    ALTER TABLE "upload_requests" ADD CONSTRAINT "upload_requests_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_requests_filled_by_id_users_id_fk' AND conrelid = 'public.upload_requests'::regclass) THEN
    ALTER TABLE "upload_requests" ADD CONSTRAINT "upload_requests_filled_by_id_users_id_fk" FOREIGN KEY ("filled_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_requests_filled_torrent_id_torrents_id_fk' AND conrelid = 'public.upload_requests'::regclass) THEN
    ALTER TABLE "upload_requests" ADD CONSTRAINT "upload_requests_filled_torrent_id_torrents_id_fk" FOREIGN KEY ("filled_torrent_id") REFERENCES "public"."torrents"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_request_fill_attempts_request_id_upload_requests_id_fk' AND conrelid = 'public.upload_request_fill_attempts'::regclass) THEN
    ALTER TABLE "upload_request_fill_attempts" ADD CONSTRAINT "upload_request_fill_attempts_request_id_upload_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."upload_requests"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_request_fill_attempts_user_id_users_id_fk' AND conrelid = 'public.upload_request_fill_attempts'::regclass) THEN
    ALTER TABLE "upload_request_fill_attempts" ADD CONSTRAINT "upload_request_fill_attempts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_request_fill_attempts_torrent_id_torrents_id_fk' AND conrelid = 'public.upload_request_fill_attempts'::regclass) THEN
    ALTER TABLE "upload_request_fill_attempts" ADD CONSTRAINT "upload_request_fill_attempts_torrent_id_torrents_id_fk" FOREIGN KEY ("torrent_id") REFERENCES "public"."torrents"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_request_comments_request_id_upload_requests_id_fk' AND conrelid = 'public.upload_request_comments'::regclass) THEN
    ALTER TABLE "upload_request_comments" ADD CONSTRAINT "upload_request_comments_request_id_upload_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."upload_requests"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_request_comments_author_id_users_id_fk' AND conrelid = 'public.upload_request_comments'::regclass) THEN
    ALTER TABLE "upload_request_comments" ADD CONSTRAINT "upload_request_comments_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'upload_request_comments_deleted_by_id_users_id_fk' AND conrelid = 'public.upload_request_comments'::regclass) THEN
    ALTER TABLE "upload_request_comments" ADD CONSTRAINT "upload_request_comments_deleted_by_id_users_id_fk" FOREIGN KEY ("deleted_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'freeleech_pool_cycles_triggered_event_id_bonus_events_id_fk' AND conrelid = 'public.freeleech_pool_cycles'::regclass) THEN
    ALTER TABLE "freeleech_pool_cycles" ADD CONSTRAINT "freeleech_pool_cycles_triggered_event_id_bonus_events_id_fk" FOREIGN KEY ("triggered_event_id") REFERENCES "public"."bonus_events"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'freeleech_pool_cycles_paused_event_created_by_id_users_id_fk' AND conrelid = 'public.freeleech_pool_cycles'::regclass) THEN
    ALTER TABLE "freeleech_pool_cycles" ADD CONSTRAINT "freeleech_pool_cycles_paused_event_created_by_id_users_id_fk" FOREIGN KEY ("paused_event_created_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'freeleech_pool_cycles_waiting_on_event_id_bonus_events_id_fk' AND conrelid = 'public.freeleech_pool_cycles'::regclass) THEN
    ALTER TABLE "freeleech_pool_cycles" ADD CONSTRAINT "freeleech_pool_cycles_waiting_on_event_id_bonus_events_id_fk" FOREIGN KEY ("waiting_on_event_id") REFERENCES "public"."bonus_events"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'freeleech_pool_contributions_cycle_id_freeleech_pool_cycles_id_fk' AND conrelid = 'public.freeleech_pool_contributions'::regclass) THEN
    ALTER TABLE "freeleech_pool_contributions" ADD CONSTRAINT "freeleech_pool_contributions_cycle_id_freeleech_pool_cycles_id_fk" FOREIGN KEY ("cycle_id") REFERENCES "public"."freeleech_pool_cycles"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'freeleech_pool_contributions_user_id_users_id_fk' AND conrelid = 'public.freeleech_pool_contributions'::regclass) THEN
    ALTER TABLE "freeleech_pool_contributions" ADD CONSTRAINT "freeleech_pool_contributions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'torrents_moderated_by_id_users_id_fk' AND conrelid = 'public.torrents'::regclass) THEN
    ALTER TABLE "torrents" ADD CONSTRAINT "torrents_moderated_by_id_users_id_fk" FOREIGN KEY ("moderated_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'torrent_favorites_user_id_users_id_fk' AND conrelid = 'public.torrent_favorites'::regclass) THEN
    ALTER TABLE "torrent_favorites" ADD CONSTRAINT "torrent_favorites_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'torrent_favorites_torrent_id_torrents_id_fk' AND conrelid = 'public.torrent_favorites'::regclass) THEN
    ALTER TABLE "torrent_favorites" ADD CONSTRAINT "torrent_favorites_torrent_id_torrents_id_fk" FOREIGN KEY ("torrent_id") REFERENCES "public"."torrents"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'user_follows_follower_id_users_id_fk' AND conrelid = 'public.user_follows'::regclass) THEN
    ALTER TABLE "user_follows" ADD CONSTRAINT "user_follows_follower_id_users_id_fk" FOREIGN KEY ("follower_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'user_follows_following_id_users_id_fk' AND conrelid = 'public.user_follows'::regclass) THEN
    ALTER TABLE "user_follows" ADD CONSTRAINT "user_follows_following_id_users_id_fk" FOREIGN KEY ("following_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tags_fts_name_idx" ON "tags" USING gin (to_tsvector('simple', coalesce("name", '')));
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hnr_user_is_hnr_idx" ON "hnr_tracking" USING btree ("user_id","is_hnr");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_imdb_idx" ON "torrents" USING btree ("imdb_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_tmdb_idx" ON "torrents" USING btree ("tmdb_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_tmdb_season_idx" ON "torrents" USING btree ("tmdb_id","season");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_grouped_idx" ON "torrents" USING btree (coalesce("moderated_at", "created_at") DESC) WHERE "torrents"."moderation_status" = 'accepted' AND "torrents"."is_active" AND ("torrents"."tmdb_id" IS NOT NULL OR "torrents"."igdb_id" IS NOT NULL OR "torrents"."openlibrary_id" IS NOT NULL);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_ungrouped_idx" ON "torrents" USING btree (coalesce("moderated_at", "created_at") DESC) WHERE "torrents"."moderation_status" = 'accepted' AND "torrents"."is_active" AND "torrents"."tmdb_id" IS NULL AND "torrents"."igdb_id" IS NULL AND "torrents"."openlibrary_id" IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_tvdb_idx" ON "torrents" USING btree ("tvdb_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_content_signature_idx" ON "torrents" USING btree ("content_signature");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_moderation_status_idx" ON "torrents" USING btree ("moderation_status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_fts_name_idx" ON "torrents" USING gin (to_tsvector('simple', coalesce("name", '')));
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_fts_description_idx" ON "torrents" USING gin (to_tsvector('simple', coalesce("description", '')));
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_fts_nfo_idx" ON "torrents" USING gin (to_tsvector('simple', coalesce("nfo", '')));
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "announce_log_created_at_idx" ON "announce_log" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "announce_log_info_hash_idx" ON "announce_log" USING btree ("info_hash");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invitations_code_idx" ON "invitations" USING btree ("code");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invitations_created_by_idx" ON "invitations" USING btree ("created_by");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrent_tags_tag_idx" ON "torrent_tags" USING btree ("tag_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_age_tiers_enabled_idx" ON "bonus_age_tiers" USING btree ("enabled");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_age_tiers_threshold_idx" ON "bonus_age_tiers" USING btree ("min_age_days");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_rules_kind_idx" ON "bonus_rules" USING btree ("kind");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_seed_count_tiers_enabled_idx" ON "bonus_seed_count_tiers" USING btree ("enabled");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_seed_count_tiers_threshold_idx" ON "bonus_seed_count_tiers" USING btree ("max_seeders");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_events_enabled_idx" ON "bonus_events" USING btree ("enabled");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_events_window_idx" ON "bonus_events" USING btree ("starts_at","ends_at");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "bonus_grants_first_seeder_unique_idx" ON "bonus_grants" USING btree ("torrent_id") WHERE source = 'first_seeder' AND torrent_id IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_grants_source_user_torrent_idx" ON "bonus_grants" USING btree ("source","user_id","torrent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "bonus_grants_user_idx" ON "bonus_grants" USING btree ("user_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "federated_follows_target_idx" ON "federated_follows" USING btree ("peer_id","remote_username");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "federated_follows_unique" ON "federated_follows" USING btree ("local_user_id","peer_id","remote_username");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "federation_peers_instance_id_unique" ON "federation_peers" USING btree ("instance_id") WHERE instance_id IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "federation_peers_status_idx" ON "federation_peers" USING btree ("status");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "federated_identities_unique" ON "federated_identities" USING btree ("local_user_id","peer_id","remote_username");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notifications_user_created_idx" ON "notifications" USING btree ("user_id","created_at" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notifications_user_unread_idx" ON "notifications" USING btree ("user_id") WHERE read_at IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "recovery_codes_user_idx" ON "recovery_codes" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "remote_torrents_content_sig_idx" ON "remote_torrents" USING btree ("content_signature");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "remote_torrents_igdb_idx" ON "remote_torrents" USING btree ("igdb_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "remote_torrents_imdb_idx" ON "remote_torrents" USING btree ("imdb_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "remote_torrents_info_hash_idx" ON "remote_torrents" USING btree ("info_hash");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "remote_torrents_name_idx" ON "remote_torrents" USING btree ("name");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "remote_torrents_openlibrary_idx" ON "remote_torrents" USING btree ("openlibrary_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "remote_torrents_peer_remote_unique" ON "remote_torrents" USING btree ("peer_id","remote_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "remote_torrents_tmdb_idx" ON "remote_torrents" USING btree ("tmdb_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "shop_items_enabled_idx" ON "shop_items" USING btree ("enabled");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "shop_purchases_item_idx" ON "shop_purchases" USING btree ("item_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "shop_purchases_user_idx" ON "shop_purchases" USING btree ("user_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrent_mod_messages_author_idx" ON "torrent_moderation_messages" USING btree ("author_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrent_mod_messages_torrent_idx" ON "torrent_moderation_messages" USING btree ("torrent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "trusted_devices_expires_idx" ON "trusted_devices" USING btree ("expires_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "trusted_devices_user_idx" ON "trusted_devices" USING btree ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "user_notification_channels_user_type_unique" ON "user_notification_channels" USING btree ("user_id","channel_type");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "user_notification_routing_pk" ON "user_notification_routing" USING btree ("user_id","type");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_notification_routing_user_idx" ON "user_notification_routing" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webauthn_credentials_user_idx" ON "webauthn_credentials" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "anticheat_flags_kind_idx" ON "anticheat_flags" USING btree ("kind");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "anticheat_flags_no_leecher_open_unique" ON "anticheat_flags" USING btree ("user_id","torrent_id") WHERE kind = 'no_leecher' AND reviewed_at IS NULL AND torrent_id IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "anticheat_flags_unreviewed_idx" ON "anticheat_flags" USING btree ("reviewed_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "anticheat_flags_user_idx" ON "anticheat_flags" USING btree ("user_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "upload_requests_filled_at_idx" ON "upload_requests" USING btree ("filled_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "upload_requests_requester_idx" ON "upload_requests" USING btree ("requester_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "upload_requests_status_idx" ON "upload_requests" USING btree ("status","created_at");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "upload_request_fill_attempts_active_unique" ON "upload_request_fill_attempts" USING btree ("request_id","user_id") WHERE status = 'proposed';
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "upload_request_fill_attempts_request_user_idx" ON "upload_request_fill_attempts" USING btree ("request_id","user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "upload_request_comments_request_idx" ON "upload_request_comments" USING btree ("request_id","created_at");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "freeleech_pool_config_singleton" ON "freeleech_pool_config" USING btree ("id") WHERE id = 1;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "freeleech_pool_windows_kind_idx" ON "freeleech_pool_windows" USING btree ("kind","enabled");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "freeleech_pool_windows_oneoff_idx" ON "freeleech_pool_windows" USING btree ("starts_at","ends_at");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "freeleech_pool_cycles_open_unique" ON "freeleech_pool_cycles" USING btree ("status") WHERE status IN ('filling', 'full_queued', 'active');
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "freeleech_pool_cycles_status_idx" ON "freeleech_pool_cycles" USING btree ("status","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "freeleech_pool_contributions_cycle_idx" ON "freeleech_pool_contributions" USING btree ("cycle_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "freeleech_pool_contributions_cycle_user_idx" ON "freeleech_pool_contributions" USING btree ("cycle_id","user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "federation_catalog_removals_cursor_idx" ON "federation_catalog_removals" USING btree ("removed_at","id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "categories_parent_idx" ON "categories" USING btree ("parent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hnr_status_idx" ON "hnr_tracking" USING btree ("is_hnr");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hnr_torrent_idx" ON "hnr_tracking" USING btree ("torrent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "hnr_user_idx" ON "hnr_tracking" USING btree ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "hnr_user_torrent_idx" ON "hnr_tracking" USING btree ("user_id","torrent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reports_reporter_idx" ON "reports" USING btree ("reporter_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reports_status_idx" ON "reports" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reports_target_idx" ON "reports" USING btree ("target_type","target_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "site_stats_created_at_idx" ON "site_stats" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_category_idx" ON "torrents" USING btree ("category_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_igdb_idx" ON "torrents" USING btree ("igdb_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "torrents_info_hash_idx" ON "torrents" USING btree ("info_hash");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_name_trgm_idx" ON "torrents" USING gin ("name" gin_trgm_ops);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_openlibrary_idx" ON "torrents" USING btree ("openlibrary_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_updated_at_idx" ON "torrents" USING btree ("updated_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrents_uploader_idx" ON "torrents" USING btree ("uploader_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "users_passkey_idx" ON "users" USING btree ("passkey");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "torrent_favorites_user_created_idx" ON "torrent_favorites" USING btree ("user_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_follows_following_idx" ON "user_follows" USING btree ("following_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_roles_role_idx" ON "user_roles" USING btree ("role_id");
--> statement-breakpoint
ALTER TABLE "remote_torrents" DROP COLUMN IF EXISTS "record_id";
--> statement-breakpoint
ALTER TABLE "remote_torrents" DROP COLUMN IF EXISTS "issuer";
--> statement-breakpoint
ALTER TABLE "remote_torrents" DROP COLUMN IF EXISTS "verified";
--> statement-breakpoint
ALTER TABLE "user_roles" DROP CONSTRAINT IF EXISTS "user_roles_user_id_role_id_pk";
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conrelid = 'public.user_roles'::regclass AND contype = 'p') THEN
    ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_role_id_pk" PRIMARY KEY("user_id","role_id");
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conname = 'roles_name_unique' AND conrelid = 'public.roles'::regclass) THEN
    ALTER TABLE "roles" ADD CONSTRAINT "roles_name_unique" UNIQUE("name");
  END IF;
END $$;
