/**
 * The autobrr indexer definition for this instance, generated.
 *
 * Same argument as the Prowlarr definition next door, one step further. That
 * one is generated because the category map is per instance; this one is
 * generated because the **announce format is per instance** — it is a template
 * an operator may edit — so a hand-written definition would be a guess about a
 * string in somebody else's database.
 *
 * The pattern comes from `announcePattern(template)`, which is the same
 * function the renderer's output is shaped by. There is no second description
 * of the format anywhere: one template produces both the line and the regex
 * that reads it, which is why the round-trip test in `test/ircAnnounce.test.ts`
 * is able to prove they agree for any template rather than for one.
 *
 * ## The test line is not decoration
 *
 * A definition carries `tests`, and autobrr's own tooling runs them. Emitting a
 * rendered sample and the values it should yield means the file we hand a member
 * arrives with a proof that it parses this instance's format — and if an
 * operator's template is unparseable by its own regex, that shows up in their
 * autobrr rather than in a silence nobody can explain.
 */
import {
  ANNOUNCE_TOKENS,
  announcePattern,
  renderAnnounce,
  templateTokens,
  type AnnounceFields,
} from './format';

/** A release that exercises every field, for the definition's self-test. */
export const SAMPLE_FIELDS: AnnounceFields = {
  name: 'Example.Release.2026.1080p.BluRay.x264-GROUP',
  category: 'Movies',
  size: '14.62 GiB',
  freeleechPercent: '100%',
  uploadFactor: '2',
  tags: '1080p, bluray, x264',
  uploader: 'example',
  url: 'https://tracker.example.com/torrents/0123456789abcdef0123456789abcdef01234567',
  infoHash: '0123456789abcdef0123456789abcdef01234567',
};

/** YAML single-quoted scalar — the form that needs no backslash escaping, which
 *  matters when the value IS a regular expression. */
function sq(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** YAML double-quoted scalar, for values that carry no backslashes. */
function dq(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

export function slugifyId(name: string): string {
  const slug = name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return slug || 'trackarr';
}

export interface AutobrrDefinitionInput {
  siteName: string;
  /** Where the member reached this instance — the definition's `urls`. */
  baseUrl: string;
  /** IRC network details, from the operator's config. */
  irc: {
    host: string;
    port: number;
    tls: boolean;
    channel: string;
    /** The bot's nick, which autobrr matches announcements against. */
    announcer: string;
    /** Whether a channel key is in use — the member has to be told to ask. */
    keyed: boolean;
    /** True when the operator configured perform lines, which usually means an
     *  invite request the member's own bot will have to make too. */
    invited: boolean;
  };
  template: string;
}

export function autobrrDefinition(input: AutobrrDefinitionInput): string {
  const id = slugifyId(input.siteName);
  const { pattern } = announcePattern(input.template);
  const tokens = templateTokens(input.template);

  // What the sample line should yield: every mapped token the template uses.
  // Built from the same table the pattern is, so a token added to the format
  // appears in the expectations without anybody remembering to add it.
  const expectations = tokens
    .map((token) => {
      const def = ANNOUNCE_TOKENS[token]!;
      if (!def.variable) return null;
      const value = SAMPLE_FIELDS[token as keyof AnnounceFields];
      return `                  ${token}: ${dq(String(value))}`;
    })
    .filter(Boolean)
    .join('\n');

  const sampleLine = renderAnnounce(input.template, SAMPLE_FIELDS);

  return `---
# Generated by ${input.siteName} — do not hand-edit.
#
# This definition is produced from the announce template in force on the
# instance, so it always matches what the channel is actually saying. If the
# operator changes the format, download it again.
#
# Drop this file in autobrr's custom definitions directory, restart autobrr,
# then add the indexer and paste your API key from ${input.baseUrl}/me.
version: 2
name: ${dq(input.siteName)}
identifier: ${id}
description: ${dq(`${input.siteName} is a private tracker`)}
language: en-us
urls:
  - ${dq(`${input.baseUrl}/`)}
privacy: private
protocol: torrent
supports:
  - irc
  - rss

settings:
  - name: apikey
    type: secret
    required: true
    label: API key
    help: ${dq('Settings → Keys → API key. Not your announce passkey: that one can announce on your behalf.')}

irc:
  network: ${dq(input.siteName)}
  server: ${dq(input.irc.host)}
  port: ${input.irc.port}
  tls: ${input.irc.tls}
  settings:
    - name: nick
      type: text
      required: true
      label: Nick
      help: ${dq('Your IRC nick. Some networks want a bot suffix, e.g. yourname|autodl.')}
    - name: auth.account
      type: text
      required: false
      label: NickServ account
      help: ${dq('Only if the network requires you to be identified.')}
    - name: auth.password
      type: secret
      required: false
      label: NickServ password
      help: ${dq('Only if the network requires you to be identified.')}
${
  input.irc.invited || input.irc.keyed
    ? `    - name: invite_command
      type: secret
      required: false
      label: Invite command
      help: ${dq('The channel is not open to everyone. Ask the operator what to send, and to whom.')}
`
    : ''
}
  channels:
    - name: ${dq(input.irc.channel)}
      announcers:
        - ${dq(input.irc.announcer)}
      parse:
        type: single
        lines:
          - pattern: ${sq(pattern)}
            tests:
              - line: ${sq(sampleLine)}
                expect:
${expectations}
        match:
          infourl: ${dq('/torrents/{{ .torrentId }}')}
          # No key travels in the announce line — everyone in the channel sees
          # it. Your own key is appended here, by autobrr, from the setting
          # above.
          downloadurl: ${dq('/api/torznab/download?id={{ .torrentId }}&apikey={{ .apikey }}')}
`;
}
