#!/usr/bin/env bash
# Refresh apps/tracker/db/schema.sql from a live PostgreSQL instance.
#
# Drizzle (in packages/db/) is the source of truth for migrations. This
# script only captures a snapshot of the columns the tracker uses, so sqlc
# can validate our queries at generation time.
#
# Usage:
#   DATABASE_URL=postgres://user:pass@host:5432/db ./apps/tracker/scripts/dump-schema.sh
#
# Or run against the local docker-compose stack:
#   ./apps/tracker/scripts/dump-schema.sh

set -euo pipefail

TRACKER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$TRACKER_DIR/db/schema.sql"

DATABASE_URL="${DATABASE_URL:-postgres://tracker:trackertest@localhost:5432/trackarr}"

# Tables the tracker reads/writes. Adding a column the tracker uses?
# Add it to the tracker's queries first, regen, and the build will tell
# you what to update here.
TABLES=(users torrents settings hnr_tracking)
TABLE_FLAGS=()
for t in "${TABLES[@]}"; do
  TABLE_FLAGS+=("--table=$t")
done

cat > "$OUT" <<EOF
-- Schema subset used by the tracker.
--
-- Generated by ./scripts/dump-schema.sh — do not hand-edit unless you
-- also update Drizzle (packages/db/src/schema.ts), the canonical source.
--
-- sqlc reads this file to validate the queries under db/queries/ at
-- generation time.

EOF

pg_dump --schema-only --no-owner --no-acl \
  --no-publications --no-subscriptions --no-tablespaces \
  "${TABLE_FLAGS[@]}" \
  "$DATABASE_URL" \
  | grep -vE '^(SET |SELECT pg_catalog|--)' \
  | sed '/^$/N;/^\n$/D' \
  >> "$OUT"

echo "✓ wrote $OUT"
